### ISSUE TITLE
Pool Owner Transactions show "receive" as "spends".

### ISSUE THREAD

**Issue by frog357** [cardanians/cexplorer.io#2]
**Describe the bug**
https://cexplorer.io/stake/stake1uylpe4yhr2wxw8g540rp9z9gwgd6su98tpxnk8upwh77l3czz5l7h/tx#data
View this page -- it shows transactions from our "Stake pool owner address".
All the transactions show red and have "-5" and appear to be "spends" from this account - however all these transactions are "receives". I believe they should be showing as +3 or maybe "Green" indicators instead of the way it's shown now - it looks like my owner address was spending 5 ADA instead of receiving ADA.

**To Reproduce**
1. View this link: https://cexplorer.io/stake/stake1uylpe4yhr2wxw8g540rp9z9gwgd6su98tpxnk8upwh77l3czz5l7h/tx#data
2. Observe the display of transactions.

**Expected behavior**
If you compare the view to this page:
https://adaex.org/address/addr1qyerleqm6uu7dyyayjp6ycffjjzcu5qgacn0fy2m58vrad37rn2fwx5uvuw3f27xz2y2susm4pc2wkzd8v0cza0aalrs2kg3mf
You can see how the display is reversed.

**Comment by cardanians** [comment]
you're right. here it's in terms of the "inputs", but it's supposed to be in terms of the address/account we're filtering. Will take a look on it ASAP.

Thanks, I appreciate it.

**Comment by cardanians** [comment]
@frog357 should be fixed now

**Comment by frog357** [comment]
Great site / great work / a valuable asset to our community!!
