### ISSUE TITLE
Incorrect metadata showing under mint for token

### ISSUE THREAD

**Issue by frog357** [cardanians/cexplorer.io#3]
**Describe the bug**
Our token should not have any metadata however we have distributed our token while minting other assets and this has created a situation where metadata is showing up for my token when I believe this should not be.

**To Reproduce**
1. View this page: https://cexplorer.io/asset/asset1rew6h8056v6zc5kzdgc9t59vxx5m44czpmqs25/metadata#data
2. Observe that metadata appears here however the policy ID for this metadata does not match the policy ID for the token we are viewing.
3. The tails token has a policy ID of: 21c26b0c4d1cb37225374c96f38df70ecffd808bbd7f1aae23d8b3e3
4. The metadata showing up has a policy ID of: 7ffffff700045d2e9ceb1c72af9d88b454ab7596f5c414b4be0296cb

**Expected behavior**
I believe this metadata should not be visible here - filter to show only metadata which is a match to the policy ID of the token.

**Comment by cardanians** [comment]
again thank you, fixed :)
