### ISSUE TITLE
Misspelled word found on Versions page

### ISSUE THREAD

**Issue by erifor** [cardanians/cexplorer.io#5]
Hello! Just found your site to watch the HFC and it's great. I love the clean design and easy navigation. I noticed the wrong word used to refer to "web scraping" and wanted you to know. 

On your mainnet Versions page I see a warning midway down the page that says:

> Scrapping of this website is not allowed without approval.

There is a BIG difference between "scrapping" something (throwing something away) and "scraping" it (taking a sample). 

Just wanted to point this out. Hope it helps! -Eric

**Comment by cardanians** [comment]
Hello @erifor thank you for feedback, we are happy you are enjoying our new website.

Issue with scraping is now (thank you!) fixed internally, will be fixed on public websites in coming days... :)
